"""initial_schema

Revision ID: 3c5a4a1fc056
Revises: 
Create Date: 2026-06-05 18:10:15.758586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5a4a1fc056'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.create_index('idx_agents_department', 'agents', ['department'], unique=False)
    op.create_index('idx_agents_enterprise', 'agents', ['enterprise_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'enterprises', ['enterprise_id'], ['id'])
    op.create_index('idx_conversations_agent', 'conversations', ['agent_id'], unique=False)
    op.alter_column('departments', 'id',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('departments', 'description',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('departments', 'color',
               existing_type=sa.VARCHAR(length=7),
               server_default=None,
               existing_nullable=True)
    op.create_index('idx_departments_enterprise', 'departments', ['enterprise_id'], unique=False)
    op.create_foreign_key(None, 'departments', 'enterprises', ['enterprise_id'], ['id'])
    op.create_index('idx_enterprise_llm_keys_enterprise_provider', 'enterprise_llm_keys', ['enterprise_id', 'provider'], unique=False)
    op.alter_column('enterprises', 'default_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('enterprises', 'default_model',
               existing_type=sa.VARCHAR(length=150),
               server_default=None,
               existing_nullable=True)
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id'], unique=False)
    op.alter_column('operation_logs', 'actor_agent_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               existing_nullable=True)
    op.create_index('idx_operation_logs_created', 'operation_logs', ['created_at'], unique=False)
    op.create_index('idx_operation_logs_enterprise', 'operation_logs', ['enterprise_id'], unique=False)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'repeat',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('tasks', 'save_conversation',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_index('idx_tasks_agent', 'tasks', ['agent_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_foreign_key(None, 'tasks', 'conversations', ['conversation_id'], ['id'])
    op.create_index('idx_user_accounts_enterprise', 'user_accounts', ['enterprise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_accounts_enterprise', table_name='user_accounts')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_agent', table_name='tasks')
    op.alter_column('tasks', 'save_conversation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('tasks', 'repeat',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'none'"),
               existing_nullable=True)
    op.alter_column('tasks', 'task_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'immediate'"),
               existing_nullable=True)
    op.drop_index('idx_operation_logs_enterprise', table_name='operation_logs')
    op.drop_index('idx_operation_logs_created', table_name='operation_logs')
    op.alter_column('operation_logs', 'actor_agent_name',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("('')"),
               existing_nullable=True)
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.alter_column('enterprises', 'default_model',
               existing_type=sa.VARCHAR(length=150),
               server_default=sa.text("('')"),
               existing_nullable=True)
    op.alter_column('enterprises', 'default_provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("('')"),
               existing_nullable=True)
    op.drop_index('idx_enterprise_llm_keys_enterprise_provider', table_name='enterprise_llm_keys')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index('idx_departments_enterprise', table_name='departments')
    op.alter_column('departments', 'color',
               existing_type=sa.VARCHAR(length=7),
               server_default=sa.text("'#06b6d4'"),
               existing_nullable=True)
    op.alter_column('departments', 'description',
               existing_type=sa.TEXT(),
               server_default=sa.text("('')"),
               existing_nullable=True)
    op.alter_column('departments', 'id',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_index('idx_conversations_agent', table_name='conversations')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index('idx_agents_enterprise', table_name='agents')
    op.drop_index('idx_agents_department', table_name='agents')
    op.alter_column('agents', 'provider',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text('("deepseek")'),
               existing_nullable=True)
    # ### end Alembic commands ###
